import requests
import ipaddress

# --- CẤU HÌNH WHITELIST CỦA BẠN ---
# Bạn có thể thêm bất kỳ IP hoặc dải IP nào muốn đi thẳng (không qua VPN) vào đây
WHITELIST = [
    "1.1.1.1/32",    # Cloudflare DNS
    "8.8.8.8/32",    # Google DNS
  ]

def get_ips(url, label):
    print(f"Dang lay du lieu tu {label}...")
    try:
        resp = requests.get(url, timeout=15)
        resp.raise_for_status()
        networks = []
        for line in resp.text.splitlines():
            line = line.strip()
            # Bỏ qua dòng trống hoặc comment
            if not line or line.startswith(('#', 'apnic|')): 
                if "apnic|VN|ipv4|" in line: # Xử lý riêng cho định dạng APNIC
                    parts = line.split('|')
                    ip, count = parts[3], int(parts[4])
                    prefix = 32 - (count.bit_length() - 1)
                    networks.append(ipaddress.ip_network(f"{ip}/{prefix}"))
                continue
            try:
                # Xử lý định dạng CIDR (1.1.1.0/24)
                networks.append(ipaddress.ip_network(line))
            except:
                continue
        return networks
    except Exception as e:
        print(f"Loi khi tai {label}: {e}")
        return []

def main():
    # 1. Định nghĩa các nguồn "Sống" (Update 2026)
    sources = [
        {"url": "https://ftp.apnic.net/stats/apnic/delegated-apnic-latest", "label": "APNIC Official"},
        {"url": "https://raw.githubusercontent.com/herrbischoff/country-ip-blocks/master/ipv4/vn.cidr", "label": "Country IP Blocks (GeoIP)"},
    ]

    all_nets = []

    # 2. Thu thập dữ liệu
    for src in sources:
        all_nets.extend(get_ips(src['url'], src['label']))

    # 3. Thêm Whitelist cá nhân
    for item in WHITELIST:
        all_nets.append(ipaddress.ip_network(item))

    print(f"Tong so dai IP tho: {len(all_nets)}")

    # 4. THUẬT TOÁN QUAN TRỌNG: Gộp dải (Aggregation)
    # Giúp RB750Gr3 giảm tải CPU cực hiệu quả
    merged_nets = list(ipaddress.collapse_addresses(all_nets))
    
    print(f"So luong dai IP sau khi toi uu: {len(merged_nets)}")

    # 5. Xuất file .rsc định dạng chuẩn Mikrotik
    with open("vn_ipv4.rsc", "w") as f:
        f.write("/ip firewall address-list\n")
        f.write("remove [find list=vn_ipv4 comment=\"AutoGenerated\"]\n") # Tùy chọn: Xóa các dòng cũ do script tạo
        for net in merged_nets:
            f.write(f"add list=vn_ipv4 address={net} comment=\"AutoGenerated\"\n")

if __name__ == "__main__":
    main()
