name: Update Mikrotik IP List

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 2 * * 0' # 2:00 sáng Chủ Nhật
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write # Quyền để xóa lịch sử

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run IP Generator
        run: python generate_ip.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add vn_ipv4.rsc
          git commit -m "🚀 Auto-update: $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
          git push

      # --- DỌN DẸP BẰNG GITHUB CLI (CHÍNH CHỦ - KHÔNG LO LỖI) ---
      - name: Delete old workflow runs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Giữ lại 3 bản chạy gần nhất, xóa toàn bộ những bản cũ hơn
          gh run list --limit 50 --json databaseId  -q '.[3:] | .[].databaseId' | xargs -I{} gh run delete {}
