name: Update Mikrotik IP List

# Vẫn giữ cái này để nếu có lỡ tay bấm nút 2 lần thì nó tự hủy bản cũ
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # XÓA PHẦN SCHEDULE Ở ĐÂY
  workflow_dispatch: # Chỉ giữ lại cái này để kích hoạt bằng tay/API

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run IP Generator
        run: python generate_ip.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add vn_ipv4.rsc
          git commit -m "🚀 Auto-update: $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
          git push

      - name: Delete old workflow runs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run list --limit 50 --json databaseId  -q '.[3:] | .[].databaseId' | xargs -I{} gh run delete {}
